01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 326:Plugin executed on: 'linux'
01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 327:Plugin executed with python version: '3.8.10 (default, Nov 14 2022, 12:59:47) \n[GCC 9.4.0]'
01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 328:KiCad build version: 6.0.7-f9a2dced07~116~ubuntu20.04.1
01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 329:Plugin version: 1.2.6
01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 330:Frame repr: <wx._core.Frame object at 0x7fbfb4199790>
01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 354:Preparing replicator with R17 as a reference
01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.replicate_layout 110:getting a list of all footprints on board
01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.replicate_layout 129:Footprint kibuzzard-63B27399 does not have Sheetfile property, it will not be replicated. Most likely it is only in schematics
01-02 22:42:41 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 369:Fatal error when making an instance of replicator
Traceback (most recent call last):
  File "/home/mkazazic/.local/share/kicad/6.0/3rdparty/plugins/com_github_MitjaNemec_ReplicateLayout/action_replicate_layout.py", line 358, in Run
    replicator = Replicator(board, src_anchor_fp_reference)
  File "/home/mkazazic/.local/share/kicad/6.0/3rdparty/plugins/com_github_MitjaNemec_ReplicateLayout/replicate_layout.py", line 153, in __init__
    self.parse_schematic_files(self.sch_filename, schematic_found)
  File "/home/mkazazic/.local/share/kicad/6.0/3rdparty/plugins/com_github_MitjaNemec_ReplicateLayout/replicate_layout.py", line 198, in parse_schematic_files
    self.parse_schematic_files(sheetfile, dict_of_sheets)
  File "/home/mkazazic/.local/share/kicad/6.0/3rdparty/plugins/com_github_MitjaNemec_ReplicateLayout/replicate_layout.py", line 179, in parse_schematic_files
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'soSPI-transformer.kicad_sch'
